### PR TITLE
Fixed an edge case in auto-approve

### PR DESCRIPTION
**Pull request by authoritydmc**
implemented better logic to disable auto approve " Hope u will like it

### CODE REVIEW

**Comment by authoritydmc** [comment]
after you merge this commit , next time onwards a fresh branch will be created.. :+1:

**Comment by authoritydmc** [comment]
What about case when we just want to check .whois not auto approve them.. well reconsider ..and if needed i will change **
if "disapprove" in event.text or "block" in event.text:
   return False 
**

**Comment by justaprudev** [comment]
Well then just disapprove..
No need to terminate autoapprove.

**Comment by authoritydmc** [comment]
@justaprudev Ok i will implement the changes now

**Comment by authoritydmc** [comment]
Done..Requested Changes .Merge Now

**Pull request merged**
